### ISSUE TITLE
nghttp timing stats

### ISSUE THREAD

**Issue by LPardue** [tatsuhiro-t/nghttp2#158]
Hi Tatsuhiro,

I see in the latest release there has been some updates to the nghttp timing stats and it looks good. I have been doing some research in this area so it comes at a good time.

When selecting the time checkpoints within nghttp, did you take inspiration from the w3c [ResourceTiming](http://www.w3.org/TR/resource-timing/) TR / [processing model](http://www.w3.org/TR/resource-timing/#processing-model)?

More specifically, I am interested to know if the response time set in on_frame_recv_callback2() is on reception of first byte or last byte of the response.

**Comment by tatsuhiro-t** [comment]
I had not read W3C TR when I implemented timing stats.

Answering your question, `on_frame_recv_callback2()` is called after response HEADERS frame was completely received.  This means that it is not exactly the time point `responseStart` described in processing model.  To more inline with the TR, we should record response time in `on_begin_headers_callback()`.

For `requetStart` it seems I did the right thing, because we record the time point in `before_frame_send_callback()` which is called just before we send the request HEADERS.
For pushed resources, we record the time in `on_begin_headers_callback` of PUSH_RPOMISE, which is also not bad choice.

For `responseEnd`, we record the time point in `on_stream_close_callback()`, which is not always the same time point described in  TR, since it might delay if request is too large and response was received before the request is half-closed.  We should record the time in `on_frame_recv_callback2()`  when we see END_STREAM flag set.

**Comment by LPardue** [comment]
OK great so we are quite close already.

For my uses it may also help to add `domainLookupEnd` and `connectStart` so that I can better understand the time required in the connection setup phase, including TCP connection reuse and TLS session reuse.

To elaborate a bit further, I am looking at applying similar timing metrics within nghttpx to get better visibility of the end-to-end performance. I think the nghttp code can translate to nghttpx with some tweaks here and there.

**Comment by tatsuhiro-t** [comment]
When I added `--har` option, which dumps timing information in HAR format, I added DNS completion, connection complete, TLS handshake timing in nghttp.  You can see `record_*` member functions in Client class.
I'll update record of timings in nghttp client to match TR's processing model.

**Comment by LPardue** [comment]
Ah yes I think I missed reading some of the values. After further inspection I can see how they map to TR's model. 

Thank you for the feedback and clarification.

**Comment by tatsuhiro-t** [comment]
Updated terminology and processing model so that they are closely matched to Resource Timing TR with this commit 9845729709cf2dff27fb9aeae16afc5d020ee745.

**Comment by LPardue** [comment]
Looks great, as always thanks!

In case you are interested and had not already seen, [this is how Chrome](https://developer.chrome.com/devtools/docs/network#resource-network-timing) uses those times and how it reports Latency / Time in the Developer Tools. Latency is time between 'action start' and responseStart. Time is time between 'action start' and responseEnd.

**Comment by tatsuhiro-t** [comment]
Thanks for suggestion.  Probably 'action start' corresponds to `startTime` in Resource Timing TR terminology (`SessionTiming.start_time` in nghttp.h).
Do you think it is useful to show latency to --stat output?

**Comment by LPardue** [comment]
For my particular use case it is not necessary to show latency but maybe it is useful for others? I'll leave that to your preference

I'm not sure how this idea of latency relates to server push. Maybe it is straightforward and handled already? The start time is triggered on push promise, so the latency is then the time until server provides the first byte of response.

**Comment by tatsuhiro-t** [comment]
OK, I'm not particularly interested in showing latency either, so leave it as is.

> I'm not sure how this idea of latency relates to server push. Maybe it is straightforward and handled already by using the * in output? The start time is triggered on push promise, so the latency is then the time until server provides the first byte of response.

I think this is reasonable.

**Comment by LPardue** [comment]
I think we are agreed and since you have kindly implemented the changes let's close this out.
