### ISSUE TITLE
nghttpx+squid with Firefox 3.6 URL append bug

### ISSUE THREAD

**Issue by nubela** [tatsuhiro-t/nghttp2#187]
Hi tatsuhiro,

On the latest master (17th March) and Firefox 36, I encountered a bug whereby every NPN protocol not working, and appending the URL twice to squid (backend).

For example, typing http://reddit.com will result in nghttpx forwarding http://reddit.comhttp://reddit.com to squid which obviously is a bug by itself.

The only temp-fix was to change npn-list to http/1.1, but thats not a good move.

Is this a bug on nghttpx or Firefox?

Thank you!

**Comment by tatsuhiro-t** [comment]
Probably firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1107881
Previously nghttpx accepts this behavior, but no longer in latest release.
We can add workaround code for this until firefox 37 comes out.
2015/03/17 2:07 "nubela" <notifications@github.com>:

**Comment by tatsuhiro-t** [comment]
According to https://wiki.mozilla.org/RapidRelease/Calendar, firefox 37 will be released at the end of this month, which includes the bug fix I mentioned previous post.  That's only less than 2 weeks, so I decided to just wait for its release rather than adding firefox <= 36 specific workaround.  For firefox 36 users, please use older version of nghttpx until upgraded into firefox 37.

**Comment by tatsuhiro-t** [comment]
Also know this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1133177.
Because of this bug, some sites cannot be loaded with firefox < 38 via HTTP/2 proxy.
So in my opinion, firefox 38 is a baseline for robust HTTP/2 proxy support.

**Comment by tatsuhiro-t** [comment]
Firefox 37 released, fixing the bug I mentioned in this thread.

**Comment by yegors** [comment]
Hi,

Is there a workaround to fix this issue in <FF37? I'm deploying a public service based on nghttpx, and not all browsers are up to date.
