### ISSUE TITLE
Authentication for proxy

### ISSUE THREAD

**Issue by wernight** [tatsuhiro-t/nghttp2#205]
Hi,

Currently I'm using [spdy-proxy](https://github.com/igrigorik/node-spdyproxy) which allows authentication.

Is there a way to have nghttpx proxy require also a user/password (basic authentication)? Is it possible to have it as a virtualhost behind Nginx so that Nginx handles that, possibly using WebSocket?

**Comment by tatsuhiro-t** [comment]
nghttpx supports SSL/TLS client certificate authentication, but no HTTP level auth.
Since you are using spdy-proxy, you are using it as so called SPDY proxy.
To make nghttpx act as SPDY/HTTP2 proxy, backend HTTP/1 proxy is required (e.g., squid).
You can enable HTTP basic auth in squid.
If  you are using nghttpx as reverse proxy, then let nginx perform authentication as you wrote.

**Comment by wernight** [comment]
Cool! Thanks. I was indeed looking for to have spdyproxy forward proxy updated to HTTP/2. So I'll try that again.
