### ISSUE TITLE
Simulate unsuccessful upgrade

### ISSUE THREAD

**Issue by lespla** [tatsuhiro-t/nghttp2#244]
Hello,
For performance test, I would like to simulate unsuccessful upgrade. 
The expected behaviour would be:
1. Request with nghttp client--> nghttp -u http://mywebserver
2. Nghttpx between nghttp client and sever--> nghttpx --client --frontend-no-tls --backend-no-tls
3. Server only running in http1

The final result would have to be upgrade request to http2 but all the next traffic would have to continue being http1
Is there any way to do it or how do you recommend to do it?

Best regards

**Comment by tatsuhiro-t** [comment]
If server is http/1, --client cannot be used, since it implies HTTP/2 server.  I think you should run nghttpx in default mode with --frontend-no-tls.

All you want to do is HTTP/1 access, and ignore 101 Upgrade success, just write HTTP/1.1 client, and ignore upgrade message.  You can copy and paste HTTP2-Settings header field from nghttp -vu output.

**Comment by lespla** [comment]
Then, are you suggesting me that I request with any browser(Firefox) to
nghttpd server and then adding the request headers upgrade?:
   Connection: Upgrade, HTTP2-Settings
   Upgrade: h2c
   HTTP2-Settings: AAMAAABkAAQAAP__
I don't know if I explained well. I want to simulate that and doing a
traffic capture.
Thanks

**Comment by tatsuhiro-t** [comment]
My understanding is that you want to send upgrade request, and server responds non-101 response (upgrade failed), and client sends another request in HTTP/1.1
Since we don't have such option in nghttp, I show some hints to achieve it manually.
Actually, just telnet to proxy, and paste the following HTTP request:
```
GET / HTTP/1.1
Host: nghttp2.org
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c-99
HTTP2-Settings: AAMAAABkAAQAAP__
Accept: */*
```

Since h2c-99 is not supported any server, it would send back 200 response, and HTTP/1.1 world continues.

Capturing traffic is a separate issue, since you can just capture the packets in background, using wireshark, dumpcap, or whatever you want.

Probably, I don't fully understand your issue.  But this is all I got so far.

**Comment by lespla** [comment]
Thanks,
I thought, maybe I could edit any server source code file for responsing
always on http1.

**Comment by tatsuhiro-t** [comment]
If you can edit nghttpx source code, then comment out the following region
https://github.com/tatsuhiro-t/nghttp2/blob/a0a5f4f93e77ae6d17708081036f5a888715f4a3/src/shrpx_https_upstream.cc#L349-L360

That would make upgrade always fail.
