### ISSUE TITLE
503 status code

### ISSUE THREAD

**Issue by nubela** [tatsuhiro-t/nghttp2#262]
On a high-load server, I'm getting occasional 503 errors from nghttpx with a Squid backend. Any idea why this happens? This is for nytimes.com btw.

    <!DOCTYPE html><html lang="en"><title>503 Service Unavailable</title><body><h1>503 Service Unavailable</h1><footer>nghttpx nghttp2/1.0.3-DEV at port 40001</footer></body></html>

**Comment by tatsuhiro-t** [comment]
Assuming you are using -s option, 503 means nghttpx cannot make connection to backend.
In high load situation, the cause is most likely the depletion of file descriptors.
Did you raise the limit of file descriptor limit per process?  What gives if you run `ulimit -n`?
The default "1024" is too small for this kind of proxy.

**Comment by nubela** [comment]
I have increased total file descriptors to 400,000.

**Comment by tatsuhiro-t** [comment]
Thanks.  Did you see "connect() failed; errno=" in nghttpx log file?
What errno you got?
Did you see other error/warning in the log file?

I saw 503 when I load tested nghttpx, that is very heavy.  It seems your site quite got heavy traffic?

**Comment by nubela** [comment]
It is definitely heavy traffic.

I do not see any error/warning. Not even connect() failed. It happens
randomly.

**Comment by tatsuhiro-t** [comment]
Upstream server could send back 503 response.
Did you see squid related header field in the response headers with 503?

**Comment by nubela** [comment]
Previously yes, Squid was the one behaving weirdly with its 503 DNS record
not found errors. And we know that it was squid because the 503 error
return a Squid interface.

However, now it is an nghttpx error page. As you can see on my first post,
the HTML returned is nghttpx's error, not squid.

**Comment by nubela** [comment]
{
type: "GET",
url: "http://www.theverge.com",
send_data: "",
send_data_json: null,
time_start: "2015-06-22T05:05:58.785217789-04:00",
send_headers: {
Proxy-Authorization: [
"Basic NmUzNzNlOTItMThiYy0xMWU1LTliZTgtMDI0MmFjMTEwMDdjOjZlMzc0MTRlLTE4YmMtMTFlNS05YmU4LTAyNDJhYzExMDA3Yw=="
]
},
status_code: 503,
response_data: "<!DOCTYPE html><html lang="en"><title>503 Service Unavailable</title><body><h1>503 Service Unavailable</h1><footer>nghttpx nghttp2/1.0.3-DEV at port 40001</footer></body></html>",
response_headers: null,
time_end: "2015-06-22T05:05:59.027402377-04:00"
}

**Comment by tatsuhiro-t** [comment]
Right, this could be still squid issue.  If nghttpx cannot connect to squid, nghttpx returns 503 with its own error page.  Currently, in this case, message is logged as INFO level.  INFO level logging produces too much data, so you probably don't want that.  The following patch will make the logging level WARN, so it could be visible:
```diff
diff --git a/src/shrpx_http_downstream_connection.cc b/src/shrpx_http_downstream_connection.cc
index 34f06b5..4570ec4 100644
--- a/src/shrpx_http_downstream_connection.cc
+++ b/src/shrpx_http_downstream_connection.cc
@@ -856,9 +856,7 @@ int HttpDownstreamConnection::on_connect() {
   if (!util::check_socket_connected(conn_.fd)) {
     conn_.wlimit.stopw();
 
-    if (LOG_ENABLED(INFO)) {
-      DLOG(INFO, this) << "downstream connect failed";
-    }
+    DLOG(WARN, this) << "downstream connect failed";
 
     return -1;
   }
```

If the reason is the squid being overloaded, then there are several options.
First, check SO_MAXCONN variable in kernel.  By default, it is too low, and easily dropped connection attempt.  If this is already adjusted, and squid is still overloaded, check its configuration (sorry, I don't know much about the configuration about squid).  You can add another squid backend with additional -b option as a last resort.

**Comment by nubela** [comment]
Lemme try.

**Comment by nubela** [comment]
Updated somaxconn values, let's see if this still reoccurs, will report in
3 days time. Thanks tatsuhiro!

**Comment by nubela** [comment]
You are right, it is squid's issue.

Just curious, are you aware if Chrome has max SPDY connections? It seems that if I try to load test with lots of streaming connections at a go, new tabs stop loading until I close the pages.

**Comment by tatsuhiro-t** [comment]
Old chrome has this issue, see Note in http://tatsuhiro-t.github.io/spdylay/package_README.html#shrpx-a-reverse-proxy-for-spdy-https
I don't know it still exists.  But theoretically, max concurrent streams are 100 by default in one SPDY session.  If you open up 100 streams, and all are active, 101th stream is just held back, waiting for the other stream is closed.

**Comment by nubela** [comment]
This is annoying, but ok, I'll close this issue. I don't think this is
nghttpx's bug.

**Comment by nubela** [comment]
Reopening this issue. So I began looking deeper into the intermittent "lags". This happens when a tab is loaded, or a link is clicked. By which Chrome will sit on "Waiting for Proxy tunnel" for a long time. And once this happens, any amount of new tabs/links being loaded will not load till it goes away.

Do you think this is nghttpx issue or Chrome's max concurrent streams issue?

**Comment by nubela** [comment]
I know in this case, it is not Squid's fault, since connecting to Squid directly on another machine or Firefox will have it load immediately.

**Comment by tatsuhiro-t** [comment]
I assume you are now reporting another issue, which is quite different from original issue, right?
I think 503 issue was closed, do you agree on this matter?

Hangging connection issue may be because of per origin host connection limit nghttpx enforces when making backend connection.  Currently, max number of connections per origin host for each frontend connection is limited to 8.

Another possible reason is flow control window is exhausted.  This could be checked using chrome net-intetnal.

**Comment by nubela** [comment]
Yes, I agree, 503 error is closed. Let me create a new issue on this.
