### ISSUE TITLE
host and authority fields together

### ISSUE THREAD

**Issue by lespla** [tatsuhiro-t/nghttp2#265]
Hello,
I don't know if it's possible send host and authority together.
I have requested:
./nghttp -v -H':host myweb.es' http://myweb.es
I get protocol error message
Isn't possible?
When I read the RFC and read :authority header  replace host header but I didn't know that happen if they were together and I have to test in my App
Best regards

**Comment by tatsuhiro-t** [comment]
I think you have to use `-H'host: myweb.es'` instead of `-H':host myweb.es' `.  But it would be a typo, since nghttp does not accept the latter.

It is completely OK to send both :authority and host.  HTTP/2 does not replace host header field with :authority, BTW.
Could be server bug.  Which server are you using for this particular experiment?

**Comment by lespla** [comment]
nghttp2 1.0.2 server

**Comment by tatsuhiro-t** [comment]
Thanks.  I tried both nghttpd and nghttpx, they work with host header.
Perhaps, you mean ":host" header field in SPDY?  Then that does not work.

**Comment by lespla** [comment]
It's my fault. I write -H'host: myweb.es' and now Works. I would think I read :host and I confused with path header
Best regards

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.
