### ISSUE TITLE
Canot hot swapping-----execve failed: errno=2

### ISSUE THREAD

**Issue by zjgood** [tatsuhiro-t/nghttp2#280]
Hello Tatsuhrio-t,
Sorry for opening this as a issue request but I could not solve this problem by various methods.
In order to accelerate the network from local to foreign , I set up a HTTP/2 Proxy( NGHTTPX ) on  server by Chrome client using your wonderful  project NGHTTP.
The problem is when I watch Youtube awhile , the network speed will become low from normal quickly,and after about several minutes  ,the network speed become normal.Cycling like this.
And I found it's efficient to fix the network speed by restart nghttpx cyclically. 
So I want to Graceful Restart nghttpx cyclically.

When I run ·" kill -USR2 $NgHTTPX_PID",
nghttpx echoed "execve failed: errno=2"

What should I do to fix it ?
Thanks for your help in advance.

**Comment by tatsuhiro-t** [comment]
Similar issue regarding slowdown or complete halt is tracked at #267 and #276.
I wonder why pretty much everyone is suffered from this issue, because I can watch 1080p youtube movie without any problem at all; no slowdown, no network problem.
I assume you built nghttpx with spdy support by linking libspdylay, is it correct?

The error came probably because you ran nghttpx without installation or not absolute path.
To restart work, nghttpx has to be started with absolute path to the nghttpx binary.

**Comment by tatsuhiro-t** [comment]
BTW, could you try Firefox with nghttpx? Firefox also supports HTTP/2 proxy.

**Comment by tatsuhiro-t** [comment]
These chrome bugs may be the cause:
https://code.google.com/p/chromium/issues/detail?id=464875
https://code.google.com/p/chromium/issues/detail?id=473259

In short, they are flow control issue on chrome side.  They say Chrome 44 may have short term workaround.

Using Firefox may be a good workaround for a while, if you can switch to Firefox.. It has different flow control approach.

**Comment by tatsuhiro-t** [comment]
Did you see "Waiting for proxy tunnel response" or something related while networking was slow?
Then this issue may be duplicate of #267.

**Comment by zjgood** [comment]
Thank you.
I run nghttpx with absolute path. It works! :+1: 
:100:
