### ISSUE TITLE
Local nghttpx client's speed was limited on 2500kbps

### ISSUE THREAD

**Issue by fourstring** [tatsuhiro-t/nghttp2#287]
I use a local nghttpx to connect a remote nghttpx,but on my chrome,I use the proxy direct,the speed which watchs YouTube can be 20000kbps,and I use the local nghttpx as a HTTP proxy on chrome,the speed was limited on 2500kbps,I want to know what cause it?How to solve it?

**Comment by tatsuhiro-t** [comment]
This is probably due to flow control.
Try increasing flow control window of local nghttpx using --backend-http2-connection-window-bits and --backend-http2-window-bits.  For example, `--backend-http2-connection-window-bits=20 and --backend-http2-window-bits=20` will increase both connection and stream level flow control window to 1MiB (2^20) from the default 64KiB.

**Comment by tatsuhiro-t** [comment]
Reopen if you still have this problem.
