### ISSUE TITLE
nghttpx: Support backend routing based on request host/path for HTTP/2 backend

### ISSUE THREAD

**Issue by tatsuhiro-t** [tatsuhiro-t/nghttp2#292]
We have implemented backend server routing based on request host/path in nghttpx #288.
Currently, it only supports HTTP/1 backend.
We'd like to see this happens in HTTP/2 backend as well.

Perhaps, --backend-http2-connections-per-worker should be renamed to --backend-http2-connections-per-group or something to limit the number of HTTP/2 connection per load balancing group, which shares the same routing host/path pattern.

**Comment by 0x64616E69656C** [comment]
Hi,

I'm playing around with this option, since I want to get rid of nginx rather sooner than later.

At the moment, I'm using nghttpx as HTTP2 frontend and TLS offloader, with nginx as backend (via http/1.1, backend=127.0.0.1,8080) to serve static files, and hhvm behind nginx for php/hack applications through fastcgi.

**What I want to do right now**:
Drop nginx for all SNI hosts which definitly do not serve PHP applications.
Use nginx as default backend for all SNI hosts which serve or might serve PHP.

[aside]
*What I want to do later:
Use HHVM either directly as nghttpx backend based on FILE/PATH (?) or behind a tiny fastcgi proxy written in go.
Use nghttpd (or some http(2)d in go) to serve static files as default backend.*
[/aside]


So I went with:
```nghttpd -D -a 127.0.0.1 -d /var/www/sni.host/ --no-tls -n2 -m100 8888```

nghttp http://sni.host:8888/ shows index.html contents - so, far so good.

in nghttpx.conf, I tried 
```
backend=127.0.0.1:8888;sni:sni.host
backend=127.0.0.1:8080
```

Which of course does not work (bad gateway for sni.host).  Is it possible to specify the desired backend communication protocol for each backend, to let nghttpx talk h2 with nghttpd and http/1 with nginx?

**Comment by tatsuhiro-t** [comment]
Currently, it is not possible to specify backend protocol per -b option.  It is defined per nghttpx instance.
The current code base heavily relies on this single backend protocol design, so we need to do some heavy lifting to achieve this.  That said, I think it is good feature addition for future release.

**Comment by kuncao** [comment]
I think it is good feature addition for future release.
-------
what's the current status of the feature?
thanks a lot

**Comment by tatsuhiro-t** [comment]
The backend protocol can be specified per -b option basis for some time now.
See https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx-b and "proto" parameter.
See also https://nghttp2.org/documentation/nghttpx-howto.html#multiple-backend-addresses
