### ISSUE TITLE
Listen on both port 80 and 443

### ISSUE THREAD

**Issue by StefanHamminga** [tatsuhiro-t/nghttp2#293]
Following up on the proxy server work I made another observation. Looking at the code there currently is no support for listening for both plain and ssl traffic, is there?
I've been testing a bit with this and took a couple of hours to write a companion server to redirect HTTP traffic on port 80 to nghttp on port 443:
https://github.com/StefanHamminga/http2https-node

I think this functionality would be nice to have (and maybe not that complicated) in the proxy itself, so to be able to also do direct HTTP upgrades. I shared the server as a proof of concept / temporary solution.

**Comment by tatsuhiro-t** [comment]
Thank you for the suggestion.
Current practice is use separate nghttpx processes for each HTTPS and HTTP (you can call it workaround for this issue).
Listen to both HTTP and HTTPS in one nghttpx instance would save extra maintenance for nghttpx process, and part of duplicated configuration file.  It needs some refactoring in nghttpx code because of some assumption that we made, but it could be possible to listen for both.  Perhaps, add new option to listen to additional plain TCP, if TLS is enabled.  The downside is most of the option in nghttpx does not take into account for this functionality.  For example, we can add custom HTTP response header field using --add-response-header option.  Sometimes we only add header to HTTPS traffic only (e.g., HSTS), or HTTP only (e.g., ALTSVC).

If using multiple nghttpx processes is OK for you, using 2 nghttpx instance for each HTTP and HTTPS works zero day.  Perhaps, we can add --include option to merge additional option values from another file, to remedy the configuration file management.

**Comment by tatsuhiro-t** [comment]
Now nghttpx can handle both HTTPS and HTTP requests.  Use extended --frontend option to configure both listening endpoints.

**Comment by romanrm** [comment]
@tatsuhiro-t Sorry but what would be the proper way to handle redirecting to HTTPS now? Same as how the OP requested a feature to do plain HTTP to HTTPS upgrade. In case both use the same plain HTTP backend, the backend doesn't know which frontend the client has used, and so whether to send the redirect or not.

@StefanHamminga were you able to solve this now just with nghttp2, without needing the http2https-node?

**Comment by tatsuhiro-t** [comment]
Backends can learn whether requests come from secure connection or not by inspecting X-Forwarded-Proto header field.  It is 'https' or 'http'.   nghttpx also supports standard Forwarded header field.

If the goal is just redirecting everything to https, then run another server on port 80, which just responds with 308 redirect.

If nghttpx is built with mruby support, redirection can be achieved with the following mruby script:

```ruby
class App
  def on_req(env)
    if env.server_port == 80
      req = env.req
      resp = env.resp
      resp.add_header 'location', 'https://<YOUR-DOMAIN>' + req.path
      resp.status = 308
      resp.return ''
    end
  end
end

App.new
```
