### ISSUE TITLE
strptime yields struct with local timezone on Mac OS X, breaking custom timegm

### ISSUE THREAD

**Issue by fwiesel** [tatsuhiro-t/nghttp2#296]
The linux man pages do not say much about the timezone of `strptime` `struct tm` output, so it is probably a bit underspecified in POSIX, but since the test works, I presume Linux defaults to UTC.
On Mac OS, it unfortunately in the local timezone.

Simply replacing `timegm` with `mktime` in one [line in parse_http_date](https://github.com/tatsuhiro-t/nghttp2/blob/master/src/util.cc#L357) does the trick for Mac OS.

But since I am not sure about the implications, I wanted to check with you, if it is acceptable to simply do it in an `#ifdef __APPLE__`?

If so, I can create a pull request for that.

Alternatively, one could try to subtract the offset after parsing the string, but I haven't look into that much.
Also, there is the boost.date_time, and since you are partly relying already on boost, it could provide the required abstraction itself. I could look into that trying to create a proposal based on that too.

**Comment by tatsuhiro-t** [comment]
Thank you for this.  I was unaware of this, and was surprised.
POSIX does not define any time zone related conversion specifier for strptime, so there is no time zone issue in their spec.  GNU has %Z and %s extensions to parse time zone, but without that (we don't use them), as far as I know, strptime just parses the string and assigns the data to the struct without time zone conversion.
So I'm curious how Mac OS X to interpret the input string and convert to local time.
If I compiled and run the following program on Linux:
```c
#define _XOPEN_SOURCE
#include <stdio.h>
#include <time.h>

int main() {
  struct tm tms;

  strptime("2015-07-15 10:11:12", "%Y-%m-%d %H:%M:%S", &tms);

  fprintf(stderr, "{%d, %d, %d, %d, %d, %d}\n", tms.tm_year + 1900,
          tms.tm_mon + 1, tms.tm_mday, tms.tm_hour, tms.tm_min, tms.tm_sec);

  return 0;
}
```

it prints out `{2015, 7, 15, 10, 11, 12}`.  If this program is compiled and run on Mac OS X, does it produce different result?
If it show the same date and time, then probably we are fine with the current code, since our timegm implementation only use the field tm_mon, tm_year, tm_yday, tm_hour, tm_min and tm_sec.

I checked out apple's strptime implementation
http://opensource.apple.com/source/Libc/Libc-997.1.1/stdtime/FreeBSD/strptime.c
I'm not sure this is the correct source code that being used.
According to this source code, if we don't use %Z and %s, no conversion is made.  So probably, we are safe.  But I'm not entirely sure what happens on Mac OS X.

**Comment by fwiesel** [comment]
It does indeed print the correct fields. It seems, my trying to fix the issue was creating a different error. Sorry for bringing you on the false track.

The actual root cause is, that the field `tm_yday` is not necessarily set, which seem to be  quite common on BSD based systems.

It will be set, however, when you parse it with the timezone,
`strptime("2015-07-15 10:11:12 GMT", "%Y-%m-%d %H:%M:%S %Z", &tms);`

Then, however, it will print `{2015, 7, 15, 12, 11, 12}`, since I am on CEST.

So, I can make the the test succeeds, if I replace  `nghttp2_timegm` with `mktime` _and_ parse the timezone (GMT).

**Comment by tatsuhiro-t** [comment]
Thank you for clarification.  I added nghttp2_timgm_without_yday, which does not use tm_yday field, and use it in parse_http_date() (see 5465cdf4a40099f6abfba6ae2b2f379f6f9730cc).
