### ISSUE TITLE
nghttp2_submit_headers allows submission to a non-existing stream

### ISSUE THREAD

**Issue by lomnicky** [tatsuhiro-t/nghttp2#297]
When calling nghttp2_submit_headers with a stream ID that does not exist, the function does not fail. Instead, it queues a HEADERS frame which is never sent due to a NGHTTP2_ERR_STREAM_CLOSED returned by session_predicate_for_stream_send when sending the frame.

Induced with 1.0.5.

**Comment by tatsuhiro-t** [comment]
This is intentional.  Since stream may get deleted after nghttp2_submit_headers(), we can defer the error handling of stream existence to when frame is dispatched.  It could simplify error handling for closed stream in on_frame_not_send_callback.
That said, do you think it is strongly effective to check stream existence on nghttp2_submit_headers() call?

**Comment by lomnicky** [comment]
Well, I don't know the background for this, but I can update my code to cope with it.
