### ISSUE TITLE
HTTP 2 :authority header overrides host for HTTP/1.1 downstreams

### ISSUE THREAD

**Issue by baranov1ch** [tatsuhiro-t/nghttp2#317]
Hi,
I've noticed that if one passes both `:authority` and `host` headers, the former will be set as `Host` value in downstream request. The spec is pretty vague about it:
```
An intermediary that converts an HTTP/2 request to HTTP/1.1 MUST create a Host header field if one is not present in a request by copying the value of the :authority pseudo-header field.
```
https://http2.github.io/http2-spec/#HttpRequest

Examples section says nothing about it directly (no clear examples), but after reading it, I am under impression that if both `host` and `:authoruty` are present, `host` should be used.
https://http2.github.io/http2-spec/#rfc.section.8.1.3

But I may be wrong... perhaps it's better to check with http wg about it?

**Comment by tatsuhiro-t** [comment]
It is true that RFC 7540 does not clarify anything about this.
My understanding is that if we get both, we should use :authority.
Some reasoning is described in RFC 7230 in https://tools.ietf.org/html/rfc7230#section-5.4

```
   When a proxy receives a request with an absolute-form of
   request-target, the proxy MUST ignore the received Host header field
   (if any) and instead replace it with the host information of the
   request-target.  A proxy that forwards such a request MUST generate a
   new Host field-value based on the received request-target rather than
   forward the received Host field-value.
```

This only states about proxy use case.
But this probably due to the fact that absolute-form is only used for proxy in HTTP/1.1 (we use origin-from for non-proxy traffic in HTTP/1.1).
