### ISSUE TITLE
PROXY protocol support on backend

### ISSUE THREAD

**Issue by rraptorr** [tatsuhiro-t/nghttp2#359]
Hello,
recently I've seen PROXY protocol support at #343 on frontend side. I also use haproxy, so this is nice news. However I'd like to request one more thing, PROXY protocol support on backend side. That way traffic can be passed cleanly through nghttpx without loosing client IP address (there is X-Forwarded-For, but it is kinda fragile and prone to errors).

**Comment by tatsuhiro-t** [comment]
nghttpx reuses backend connections between different frontend connection.  So there is no 1:1 relationship between them, and in this case PROXY protocol has almost no value.
For HTTP/2 backend, nghttpx even coalesces multiple requests from different client to single backend connection.

Because of this, usage of X-Forwarded-For is recommended.  nghttpx has `--strip-incoming-x-forwarded-for` option, which strips any incoming X-Forwarded-For and just add client address we got from PROXY protocol or socket address.  This would make X-Forwarded-For less fragile.

**Comment by rraptorr** [comment]
Right, I've missed that. I already have a working X-Forwarded-For setup but was hoping to simplify some things. Thanks anyway:)
