### ISSUE TITLE
Two instances of nghttpx running

### ISSUE THREAD

**Issue by 0x64616E69656C** [tatsuhiro-t/nghttp2#371]
Hi,

at first I thought this was due to the changes in the init script, but even starting nghttpx from command line starts 2 processes. pgrep -P / ps --pid <pid_from_pid_file> shows the second process as a child process, but killing the parent process does not kill the child process. I'm not sure if this is on porpose, or if something went wrong on my side, but this seems very new, I was used to having just one instance of nghttpx running. Can you shed some light on this? Thanks!

**Comment by 0x64616E69656C** [comment]
nevermind, that's the "Hot swapping". Not sure though, if the forked process should end when the parent process dies?

**Comment by tatsuhiro-t** [comment]
Since 1.3.3, nghttpx became multi-process:

> nghttpx now consists of 2 processes. One process is called master process, and reads configuration, and setup listening ports. It spawns a process called worker process, which handles all networking operations from remote clients. The latter drops privileges if –user is specified. The master process does not drops privileges so that when new process using new binary is spawned from master process as hotswap, it can still read private keys which requires privileged user permission.

Usually, if parent process is killed, child process detects that and exits itself, except they are in graceful shutdown mode.  Hopefully, we can eliminate this exception in the upcoming release.

BTW, we integrated [neverbleed](https://github.com/h2o/neverbleed/) support in nghttpx.
It is disabled by default.  If it is enabled, nghttpx spawns yet another process if TLS is configured.  So it consists of 3 processes.

**Comment by 0x64616E69656C** [comment]
thanks for clearing that up :)
