### ISSUE TITLE
Comparing HTTP/2 and HTTP/1.1

### ISSUE THREAD

**Issue by pcolenbr** [tatsuhiro-t/nghttp2#387]
Hello everyone,

I am doing a college project where I need to compare the behavior and the load time between HTTP/1.1 and HTTP/2.

Since I couldn't configure a serve that executes both protocols at the same time (there was Apache with mod_h2, but I had a lot of problem and couldn't get it running), I decided to use Nginx for HTTP/1.1 and the NGHTTPD for HTTP/2.

I loaded the same page using both protocols and I was surprise to notice that the load time for the page using HTTP/2 was higher! Than I took a look at the waterfall charts for both protocols and the HTTP/2 definitely had a better parallelism, but it got a worse load time anyway.

The only way I found to explain this is that the servers are different, and that Nginx has a better performance than NGHTTPD, so even though HTTP/2 is faster the final serving that is worse.

Am I right? Can you guys explain why is HTTP/2 getting a worse performance than HTTP/1.1?

Thank you all and great job with this project!

HTTP/2
![http2](https://cloud.githubusercontent.com/assets/8920720/10433775/10f09c9c-70eb-11e5-9235-8acd6a0463cd.PNG)

HTTP/1.1
![http11](https://cloud.githubusercontent.com/assets/8920720/10433777/16b8e3aa-70eb-11e5-9a68-69a31eac0d93.PNG)

**Comment by fegemo** [comment]
@pcolenbr, what does the gray portions of the bars mean?

**Comment by pcolenbr** [comment]
Legend:
 - Purple: Waiting time
 - Grey: Download time
 - Brown: Blocking time

**Comment by tatsuhiro-t** [comment]
So red line is page load, and blue line is domContentLoaded right?
There are several reasons why you get this result.
First, HTTP/2 is faster than HTTP/1.1 with real world latency.  If you do the test using LAN, then HTTP/1.1 could be faster, and HTTP/2 does not optimize download time itself.
Second, since HTTP/2 multiplexes all resource requests in one connection, the priority scheduling of critical resources are very very important for page load time (first paint, domContentLoaded).
nghttp2 implements HTTP/2 prioritization mechanism, and if client prioritizes requests so that it optimizes page load time, you probably get faster domContentLoaded time.
The problem is the only browser which implements this priority handling is Firefox.
Chrome and Edge are very bad, and it really makes contention between critical resources like js and images.

**Comment by LPardue** [comment]
> Nginx for HTTP/1.1 and the NGHTTPD for HTTP/2.

Nginx 1.9.5 supports HTTP/2 over TLS (you could do `listen 443 ssl` and `listen 444 ssl http2` to have two different instances running.). It would be interesting to see if you get similar results when using the same server implementation. Especially given that the page load time is very close between the two results you presented.

**Comment by pcolenbr** [comment]
@LPardue Thank you very much for your advice!

I just configured the Nginx 1.9.5 with HTTP/2 over TLS! I still didn't reproduce my tests to see if the page load time is going to be better, but even if it is not this will validate my project!

Thanks again!
