### ISSUE TITLE
Building a static binary doesn't work

### ISSUE THREAD

**Issue by IanLewis** [tatsuhiro-t/nghttp2#392]
I attempted to build the servers as static binaries.

    $ ./configure --enable-static

nghttpx was build a static binary and running ldd on it looks ok:

    $ ldd src/nghttpx
    	not a dynamic executable

However when I try to run it in a Docker container:

    $ cat <<EOF
    > FROM scratch
    > ADD src/nghttpx /nghttpx
    > ENTRYPOINT ["/nghttpx", "--help"]
    > CMD []
    EOF >> Dockerfile
    $ docker build -t nghttpx .

 the app crashes:

    $ docker run nghttpx
    no such file or directory
    Error response from daemon: Cannot start container xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: [8] System error: no such file or directory

If I run strace I can see that the app opens libnghttp2.so.14.

    $ strace -e trace=open nghttp2/src/nghttpx --help
    ...
    open(".../nghttp2/lib/.libs/libnghttp2.so.14", O_RDONLY|O_CLOEXEC) = 3
    ...

Moving this file locally to a different location and then running nghttpx does indeed crash the program. I guess this library is being opened dynamically in the program. Is there another way that I can build nghttpx as a static binary?

**Comment by tatsuhiro-t** [comment]
> $ ./configure --enable-static

This just enables static library of libnghttp2, and it is enabled by default, so effectively noop.

> $ ldd src/nghttpx
>    not a dynamic executable

This is because src/nghttpx is a shell script made by libtool to do some magic stuff if it is built with shared lib.  The real executables are placed under src/.libs

It seems there is no easy way to build completely static build as long as we use libc (you will get warning when you do what I say next paragraph).
But with the following patch, and additional configure flag can create seemingly static build of nghttpx.

```patch
diff --git a/src/Makefile.am b/src/Makefile.am
index 627a944..2e5f246 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -150,7 +150,8 @@ libnghttpx_a_CPPFLAGS = ${AM_CPPFLAGS}
 
 nghttpx_SOURCES = shrpx.cc shrpx.h
 nghttpx_CPPFLAGS = ${libnghttpx_a_CPPFLAGS}
-nghttpx_LDADD = libnghttpx.a ${LDADD}
+nghttpx_LDADD = libnghttpx.a ${LDADD} -ldl
+nghttpx_LDFLAGS = -all-static
 
 if HAVE_MRUBY
 libnghttpx_a_CPPFLAGS += \
```

and run `autoreconf`, and `./configure --without-jemalloc`.

You will get warning like this while building nghttp2:
```
libnghttpx.a(libnghttpx_a-shrpx_worker_process.o): In function `shrpx::worker_process_event_loop(shrpx::WorkerProcessConfig*)':
/home/tatsuhiro/workspace/nghttp2/src/shrpx_worker_process.cc:67: warning: Using 'initgroups' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
So it is not completely static, but if you build and run nghttpx with compatible libc, then it probably work.
I think building nghttp2 under Docker container is a lot easier.

**Comment by IanLewis** [comment]
I realized that it was a bash script this morning. Thanks for the info.
Building under a Docker container is indeed easier but includes all compile time components so it's very large. It would end up being on the order of 200+MB just for a program that is maybe 10+MB.

**Comment by tatsuhiro-t** [comment]
I agree your argument about docker image size.
FYI, there is a way to reduce the size https://www.dajobe.org/blog/2015/04/18/making-debian-docker-images-smaller/
