### ISSUE TITLE
Architecture Help 

### ISSUE THREAD

**Issue by sanxzkid** [tatsuhiro-t/nghttp2#423]
I'm working in a academic project using this http2 implementation and need some help.
I need to change a socket option (setsockopt) for each server response but I cannot find the exactly part of code to do this.
Regards

**Comment by tatsuhiro-t** [comment]
If you mean you want to change setsockopt for each HTTP response from server, it is a bit hard since we may send many response headers in one write call.
If you just want to change setsockopt for each client connection, search "accept" or "accept4" system call.

**Comment by sanxzkid** [comment]
I need this to define http2 prioritization on tcp/ip. This is the reason that I need to change socket options in each frame or at least in data frames. Can you help me?

**Comment by tatsuhiro-t** [comment]
I'm not sure I understand your comment.
HTTP/2 prioritization as stated in RFC 7540 does not require any TCP/IP option intervention.  It is expressed in HTTP/2 frame.

**Comment by sanxzkid** [comment]
I know, in my research we try to use HTTP2 prioritization in TCP/IP level
to use it in router prioritization for each frame.

On Wed, Nov 11, 2015 at 11:47 AM, Tatsuhiro Tsujikawa <
notifications@github.com> wrote:

> I'm not sure I understand your comment.
> HTTP/2 prioritization as stated in RFC 7540 does not require any TCP/IP
> option intervention. It is expressed in HTTP/2 frame.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tatsuhiro-t/nghttp2/issues/423#issuecomment-155788481>
> .
>



-- 
*Felipe Sanchez*
*Software Engineer*

f.sanxz@gmail.com
+55 11 982077066

**Comment by tatsuhiro-t** [comment]
OK, but it is hard to do this with nghttpd/nghttpx since we first write multiple frames into buffer, and write them at once.
The http/2 frame is usually small, and writing each of them one by one with write() with TCP_NODELAY on kills performance.

**Comment by sanxzkid** [comment]
I understand the risk of use TCP_NODELAY and I don't pretend to use. I just
need know where buffer is sent and how to read all prio into buffer and
calculate a new prioritization as IP_TOS based on HTTP/2 prio.

On Fri, Nov 13, 2015 at 1:19 PM, Tatsuhiro Tsujikawa <
notifications@github.com> wrote:

> OK, but it is hard to do this with nghttpd/nghttpx since we first write
> multiple frames into buffer, and write them at once.
> The http/2 frame is usually small, and writing each of them one by one
> with write() with TCP_NODELAY on kills performance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tatsuhiro-t/nghttp2/issues/423#issuecomment-156460621>
> .
>



-- 
*Felipe Sanchez*
*Software Engineer*

f.sanxz@gmail.com
+55 11 982077066

**Comment by tatsuhiro-t** [comment]
I'll explain where we write frame into buffer in case of nghttpd.  nghttpx has the similar architecture, but it is a bit involved.

For non-DATA frames, we write each frame in buffer here https://github.com/tatsuhiro-t/nghttp2/blob/fe8720341d3d2c486a1aaceef63039cdeecbb77f/src/HttpServer.cc#L450

So data[3] is the frame type.  If you want to send each frame per packet, then insert break at https://github.com/tatsuhiro-t/nghttp2/blob/fe8720341d3d2c486a1aaceef63039cdeecbb77f/src/HttpServer.cc#L456

For DATA frames, we write them into buffer in the function https://github.com/tatsuhiro-t/nghttp2/blob/fe8720341d3d2c486a1aaceef63039cdeecbb77f/src/HttpServer.cc#L1342

You should return NGHTTP2_ERR_PAUSE instead of 0 at https://github.com/tatsuhiro-t/nghttp2/blob/fe8720341d3d2c486a1aaceef63039cdeecbb77f/src/HttpServer.cc#L1389

Actual write call is https://github.com/tatsuhiro-t/nghttp2/blob/fe8720341d3d2c486a1aaceef63039cdeecbb77f/src/HttpServer.cc#L500 for cleartext TCP, and https://github.com/tatsuhiro-t/nghttp2/blob/fe8720341d3d2c486a1aaceef63039cdeecbb77f/src/HttpServer.cc#L628 for SSL/TLS connection.

Good luck.

**Comment by tatsuhiro-t** [comment]
Please reopen this issue if you still require any support.

**Comment by sanxzkid** [comment]
I have some
