### ISSUE TITLE
How can large incoming data be handeled with the asio library

### ISSUE THREAD

**Issue by timatooth** [tatsuhiro-t/nghttp2#427]
Thanks for making the high level asio library.
I'm trying to save PNG tiles (for a html canvas drawing app) using the ASIO server lib (1.4.0). I'm struggling to save incoming data when the request.on_data callback gets called more than once.

If it's a small PNG data request e.g < 1.5 kb it's saved correctly. But when on_data is called more than once the saved file appears to be memory junk. My C++ is not too great hence all the C style stuff which is most likely the problem. I could not find any examples of how to handle uploaded data from PUT/POST/PATCH data in the server examples.

The code
https://gist.github.com/timatooth/87af03c5269753f596ac

**Comment by tatsuhiro-t** [comment]
This is because "offset" is captured by value.

offset is defined in https://gist.github.com/timatooth/87af03c5269753f596ac#file-udrawd-cpp-L52
And it is captured by value at https://gist.github.com/timatooth/87af03c5269753f596ac#file-udrawd-cpp-L55
And len is added to offset at https://gist.github.com/timatooth/87af03c5269753f596ac#file-udrawd-cpp-L62
Since offset is captured by value, on_data callback will see the same value when it is invoked each time.
To survive multiple callbacks, we have to define offset in free store (heap).
In this case, `std::shared_ptr<size_t>` is very handy.

**Comment by timatooth** [comment]
Thanks so much! I've changed the code to use the ```std::shared_ptr<size_t>```. I also made a silly mistake in the memcpy not using the offset to move along.. :sleepy:. Would using a ```std::shared_ptr<std::vector<uint8_t>>``` as an expanding buffer and use insert(end, data, len) to copy the bytes into work better as well? Otherwise everything is working great now!

**Comment by tatsuhiro-t** [comment]
In this case, using std::vector makes code cleaner since it can manage buffer for you.
If you know the length of incoming data, std::vector::reserve will do good optimization.

**Comment by timatooth** [comment]
Great I'll definitely try that out. Thanks again for the help.
