### ISSUE TITLE
nghttpx does not preserve trailers when backend is h2 and frontend is http/1

### ISSUE THREAD

**Issue by louiscryan** [tatsuhiro-t/nghttp2#453]
Fairly simple to reproduce...

// Run webserver and force a trailer
src/nghttpd -v -d . --trailer='foo: bar' --no-tls 8080

// Run nghttpx proxy in client mode
src/nghttpx --log-level=INFO --client --backend-no-tls -b localhost,8080 -f localhost,8081

// Test using h2 to proxy. Works shows trailers
src/nghttp -v http://localhost:8080/README

// Test using h1 to proxy. Trailers not output
curl -v --raw http://localhost:8081/README

**Comment by tatsuhiro-t** [comment]
Yes..
In HTTP/1.1, we need chunked encoding to send trailer fields.  nghttpx currently does chunked encoding to client only when backend response without content-length.  Probably, we can force chunked encoding if trailer header field exists in response headers.
I thought that gRPC response does not bear content-length, is that right?  I think that is the only real use case for trailers for now.

FYI, curl with HTTP/2 does not support trailers yet.

**Comment by louiscryan** [comment]
Grpc isn't sending content-length so is it  possible you might be inferring
it if the response is small enough?

Grpc doesn't send the 'trailers' header as its pure overhead in h2. The
client does send 'TE: trailers' which is a hint that the client is
willing/expecting to receive them.

-louis (from phone)

**Comment by tatsuhiro-t** [comment]
OK, then if gRPC server sits behind nghttpx, curl HTTP/1.1 should get trailer fields in chunked encoding.
If there is no content-length from backend, nghttpx will use chunked encoding to forward response to the client, including trailer fields.
nghttpd by default adds content-length, so your reproduction step always omit trailer fields from response sent to client.

I think usually content-length is omitted when trailer fields are used since trailer is usually useful for dynamic content, and we cannot supply header fields in advance.

I think sending 'trailers' in HTTP/2 is still SHOULD since we don't change this semantics from HTTP/1.1.

https://tools.ietf.org/html/rfc7230#section-4.4
```
4.4.  Trailer

   When a message includes a message body encoded with the chunked
   transfer coding and the sender desires to send metadata in the form
   of trailer fields at the end of the message, the sender SHOULD
   generate a Trailer header field before the message body to indicate
   which fields will be present in the trailers.  This allows the
   recipient to prepare for receipt of that metadata before it starts
   processing the body, which is useful if the message is being streamed
   and the recipient wishes to confirm an integrity check on the fly.

     Trailer = 1#field-name
```

**Comment by louiscryan** [comment]
You're right that nghttpd was adding content-length. When I switched back to using the grpc server it worked fine.

See
https://gist.github.com/louiscryan/26c08bdcf295ba4f8e2a

I agree that absence of Content-Length is the right way to infer chunked encoding so marking as closed as this is working.
