### ISSUE TITLE
h2load input file number of url limitation

### ISSUE THREAD

**Issue by superzelda** [tatsuhiro-t/nghttp2#503]
not sure the exactly number of different url limitation, however when it is larger than 50,000, the error message is "invalid URI: http://cd-beap2.cbs.cb.bf1.yahoo.com/mbcsc?bv=1.0.0&es=[ERROR]: Error generating enc/signing context curveball.beap.encryption.key for thread 139921669785568"

**Comment by tatsuhiro-t** [comment]
The error is not number of URIs.  The error comes because URI `http://cd-beap2.cbs.cb.bf1.yahoo.com/mbcsc?bv=1.0.0&es=[ERROR]: Error generating enc/signing context curveball.beap.encryption.key for thread 139921669785568` is malformed.

For example, URI cannot contain white space, and it should be encoded like `%20`.

**Comment by superzelda** [comment]
if the number is less than 10,000. It's working fine, there is no such error. so I suspect the encoding and decoding occupy many thread resources. I keep the same format, only difference is the number.

**Comment by tatsuhiro-t** [comment]
I suspect that the malformed URI exist after 10,000 lines.  In other words, all URIs up to 10,000 lines are good, and at least one URIs after those lines there exists malformed URI like the one you described above.  Can you check this?

**Comment by superzelda** [comment]
you are right, I double check my weblog files, and some URIs are malformed. thanks a lot
