### ISSUE TITLE
How do I send headers with HPACK?

### ISSUE THREAD

**Issue by fatjimmy** [tatsuhiro-t/nghttp2#524]
I want to send headers that have been compressed by HPACK to sever. But I didn't find the API to make it. I found that nghttp2_submit_request could send headers but it takes a parameter nghttp2_nva array. And HPACK can only compress the headers to one buffer. So how can I send headers as I want?

**Comment by tatsuhiro-t** [comment]
Are you asking us how to create array of nghttp2_nv?
If so, the following link might help: https://gist.github.com/tatsuhiro-t/17257c3fe06519c5ee51#file-tcp-client-c-L505

**Comment by fatjimmy** [comment]
Sorry, I didn't make myself understood. Actually I'm writing a program sending notifications to apple. And 

>APNs requires the use of HPACK (header compression for HTTP/2), which prevents repeated header keys and values.

> So I know how to create array of nghttp2_nv, and I also know how to use nghttp2 API for HPACK, but nghttp2_hd_deflate_hd can only output a buffer, which cannot be sent by nghttp2_submit_request . So if I use nghttp2_hd_deflate_hd to compress array of nghttp2_nv, which API could I use to send out this buffer ?

**Comment by fatjimmy** [comment]
I made a mistake. I didn't notice the flag of enum nghttp2_nv_flag, which can set the way how headers can be compressed by HPACK. And Thank you !

**Comment by tatsuhiro-t** [comment]
For the record, to send frames, use nghttp2_session_mem_send().  It seems you just want encoded header block, if it is true, then use nghttp2_hd_deflate_hd() and send its buffer using write(2) is a good choice.

**Comment by vgmahajanshetty** [comment]
Hi,

I want to send response to a http2 client. I'm using nghttp2_submit_response() api to send headers. For this function, third parameter is nghttp2_nv *nva. If in the flag nva->flags NGHTTP2_NV_FLAG_NO_INDEX is NOT set,  then does nghttp2_submit_response() api compresses headers by HPACK and sends it? Or should we use nghttp2_hd_deflate_hd() for this purpose?

One more question I have is whether compression of headers is must in HTTP2? I'm asking this because I'm not using nghttp2_hd_deflate_hd() in my server, but it's working fine and browser is displaying the page properly and I can see all headers sent by server in wireshark on client side.

Thank you.

**Comment by tatsuhiro-t** [comment]
> does nghttp2_submit_response() api compresses headers by HPACK and sends it? Or should we use nghttp2_hd_deflate_hd() for this purpose?

nghttp2 library internally encodes given http header fields automatically.  You don't have to use nghttp2_hd_deflate_hd() directly.

> One more question I have is whether compression of headers is must in HTTP2?

Yes, it is must have.  I say MUST because both endpoint must use HPACK mechanism to encode or decode header fields.  You can write HPACK implementation so that it does not compress anything.  For nghttp2, it always compresses given http header fields.  With NGHTTP2_NV_FLAG_NO_INDEX, it disables a part of compression mechanism.

**Comment by kunalekawde** [comment]
@tatsuhiro-t , As I understand from above, there is no way to disable HEADER COMPRESSION, basically we see that wireshark capture taken in-between HTTP/2 transfers doesn't decode and show the headers properly as its compressed and data not available to wireshark. I suppose it also means static table cannot be used for headers. How can NGHTTP2_NV_FLAG_NO_INDEX be used ? I'm using libcurl.
